rutas_sugeridas:
    path:     /rutas_sugeridas
    defaults: { _controller: RutasBundle:RutasSugeridas:mostrar }

crea_tus_rutas:
    path:     /crea_tus_rutas
    defaults: { _controller: RutasBundle:CreaTusRutas:mostrar }
