rutas_sugeridas:
    path:     /rutas_sugeridas
    defaults: { _controller: RutasBundle:RutasSugeridas:mostrar }

crea_tus_rutas:
    path:     /crea_tus_rutas
    defaults: { _controller: RutasBundle:CreaTusRutas:mostrar }
    
home:
    path:     /home
    defaults: { _controller: RutasBundle:Sitios:obtenerUltimosSeis }

contactenos:
    path:     /contactenos
    defaults: { _controller: RutasBundle:Contactenos:mostrar }    

quienes_somos:
    path:     /quienes_somos
    defaults: { _controller: RutasBundle:QuienesSomos:mostrar }
    
sitios:
    path:     /sitios
    defaults: { _controller: RutasBundle:Sitios:mostrar }   
    
enviar_correo:
    path:     /correo
    defaults: { _controller: RutasBundle:Contactenos:enviarCorreo }  
    
mapa_del_sitio:
    path:     /mapa_del_sitio
    defaults: { _controller: RutasBundle:MapaDelSitio:mostrar }  