<?php

namespace Proxies\__CG__\Rutica\DataBaseBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class RutaSugerida extends \Rutica\DataBaseBundle\Entity\RutaSugerida implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Rutica\\DataBaseBundle\\Entity\\RutaSugerida' . "\0" . 'id', '' . "\0" . 'Rutica\\DataBaseBundle\\Entity\\RutaSugerida' . "\0" . 'nombre', '' . "\0" . 'Rutica\\DataBaseBundle\\Entity\\RutaSugerida' . "\0" . 'distancia', '' . "\0" . 'Rutica\\DataBaseBundle\\Entity\\RutaSugerida' . "\0" . 'precioTotal', '' . "\0" . 'Rutica\\DataBaseBundle\\Entity\\RutaSugerida' . "\0" . 'tiempo', '' . "\0" . 'Rutica\\DataBaseBundle\\Entity\\RutaSugerida' . "\0" . 'idProvincia');
        }

        return array('__isInitialized__', '' . "\0" . 'Rutica\\DataBaseBundle\\Entity\\RutaSugerida' . "\0" . 'id', '' . "\0" . 'Rutica\\DataBaseBundle\\Entity\\RutaSugerida' . "\0" . 'nombre', '' . "\0" . 'Rutica\\DataBaseBundle\\Entity\\RutaSugerida' . "\0" . 'distancia', '' . "\0" . 'Rutica\\DataBaseBundle\\Entity\\RutaSugerida' . "\0" . 'precioTotal', '' . "\0" . 'Rutica\\DataBaseBundle\\Entity\\RutaSugerida' . "\0" . 'tiempo', '' . "\0" . 'Rutica\\DataBaseBundle\\Entity\\RutaSugerida' . "\0" . 'idProvincia');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (RutaSugerida $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistancia($distancia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistancia', array($distancia));

        return parent::setDistancia($distancia);
    }

    /**
     * {@inheritDoc}
     */
    public function getDistancia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistancia', array());

        return parent::getDistancia();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecioTotal($precioTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecioTotal', array($precioTotal));

        return parent::setPrecioTotal($precioTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecioTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecioTotal', array());

        return parent::getPrecioTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setTiempo($tiempo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTiempo', array($tiempo));

        return parent::setTiempo($tiempo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTiempo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTiempo', array());

        return parent::getTiempo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProvincia(\Rutica\DataBaseBundle\Entity\Provincia $idProvincia = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProvincia', array($idProvincia));

        return parent::setIdProvincia($idProvincia);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProvincia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProvincia', array());

        return parent::getIdProvincia();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
